language: python
jobs:
  include:
  - name: "3.6 Unit Tests"
    python: "3.6"
    env: TOX_ENV=py36
  - name: "3.7 Unit Tests"
    python: "3.7"
    env: TOX_ENV=py37
  - name: "3.8 Unit Tests"
    python: "3.8"
    env: TOX_ENV=py38
  - name: "Pep8 tests using Flake8"
    python: "3.7"
    env: TOX_ENV=pep8
install:
  - pip install tox
script:
  - tox -e $TOX_ENV
