#!/bin/bash
VLAN_EXISTS=$(sudo ovs-vsctl list-br | grep "br-vlan")

if [ -z "$VLAN_EXISTS" ]
then
	echo "[+] Creating vlan bridge"
	ovs-vsctl add-br br-vlan

	echo "[=] Attaching patch ports"
	ovs-vsctl add-port br-vlan phy-br-vlan
	ovs-vsctl add-port br-int int-br-vlan

	echo "[=] Connecting patch ports"
	ovs-vsctl set interface phy-br-vlan type=patch
	ovs-vsctl set interface phy-br-vlan options:peer=int-br-vlan
	ovs-vsctl set interface int-br-vlan type=patch
	ovs-vsctl set interface int-br-vlan options:peer=phy-br-vlan

	echo "[=] VLAN bridge configured"
fi

echo "[+] Writing bridge_mappings"

SEDOUT=$(sed "s/bridge_mappings=.*/bridge_mappings=public:br-ex,networkA:br-vlan/" /etc/neutron/plugins/ml2/ml2_conf.ini)

NETWORK_A_EXISTS=$(openstack network list | grep "networkA")

if [ -z "$NETWORK_A_EXISTS"]
then
	echo "Creating NetworkA"
fi
